//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest2
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitapYazar
    {
        public int KitapYazarId { get; set; }
        public Nullable<int> KitapFkId { get; set; }
        public Nullable<int> YazarFkId { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        public virtual Yazar Yazar { get; set; }
    }
}
