//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest2
{
    using System;
    using System.Collections.Generic;
    
    public partial class KutuphaneBilgi
    {
        public int KutuphaneId { get; set; }
        public string KutuphaneAdi { get; set; }
    }
}
