//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneEntities1 : DbContext
    {
        public KutuphaneEntities1()
            : base("name=KutuphaneEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Kitap> Kitap { get; set; }
        public virtual DbSet<KitapYazar> KitapYazar { get; set; }
        public virtual DbSet<KutuphaneBilgi> KutuphaneBilgi { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<Uye> Uye { get; set; }
        public virtual DbSet<YayinEv> YayinEv { get; set; }
        public virtual DbSet<Yazar> Yazar { get; set; }
    }
}
