//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int RezervId { get; set; }
        public Nullable<int> RezervUyeFkId { get; set; }
        public Nullable<int> RezervKitapFkId { get; set; }
        public Nullable<int> ReservSure { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
